window.YUUKICHIYA_LINE_CONFIG = {
  liffId: "2010371637-PcIXzbgC",
  officialLineUrl: "https://lin.ee/7byeeeA",
  memberPageUrl: "https://makoban.github.io/yuukichiya-line-demo/?screen=member",
  pointsPageUrl: "https://makoban.github.io/yuukichiya-line-demo/?screen=points",
  staffPageUrl: "https://makoban.github.io/yuukichiya-line-demo/staff.html",
  measurementReservationUrl: "https://liff.line.me/2010371637-PcIXzbgC",
  reservationApiUrl: "https://yuukichiya-reservation-api.ai-fudosan.workers.dev/reservations",
  reservationStores: ["本店", "高橋店"],
  reservationStartHour: 10,
  reservationEndHour: 18,
  measurementRecordsPageUrl: "",
  ecUrl: "https://yuukichiya.base.shop/",
  couponPageUrl: "",
};
